In [1]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
import pandas as pd
from sklearn.compose import ColumnTransformer
import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\new\\OneDrive\\Desktop\\Ds\\EDA\\Adult EDA\\Perfect_Adult_cleaned_dataset.csv")

In [3]:
df.drop(df.columns[0],axis=1,inplace=True)

In [6]:
df.head()

Age          Workclass  Fnlwgt  Education-num          Occupation  \
0   39          State-gov   77516             13        Adm-clerical   
1   50   Self-emp-not-inc   83311             13     Exec-managerial   
2   38            Private  215646              9   Handlers-cleaners   
3   53            Private  234721              7   Handlers-cleaners   
4   28            Private  338409             13      Prof-specialty   

     Relationship    Race      Sex  Capital-gain  Capital-loss  \
0   Not-in-family   White     Male          2174             0   
1         Husband   White     Male             0             0   
2   Not-in-family   White     Male             0             0   
3         Husband   Black     Male             0             0   
4            Wife   Black   Female             0             0   

   Hours-per-week  Native-country  Income  
0              40   United-States   <=50K  
1              13   United-States   <=50K  
2              40   United-States   <=50K  
3              40   United-States   <=50K  
4              40            Cuba   <=50K

In [28]:
tnf1=ColumnTransformer(transformers=[
    ("Handling Int-Missing values",SimpleImputer(),['Age','Fnlwgt','Education-num','Capital-gain','Capital-loss','Hours-per-week']),
    ("Handling Cat-Missing values",SimpleImputer(strategy='most_frequent'),['Workclass','Occupation','Relationship','Race','Sex','Native-country'])
],remainder='passthrough')

In [29]:
tnf1

ColumnTransformer(remainder='passthrough',
                  transformers=[('Handling Int-Missing values', SimpleImputer(),
                                 ['Age', 'Fnlwgt', 'Education-num',
                                  'Capital-gain', 'Capital-loss',
                                  'Hours-per-week']),
                                ('Handling Cat-Missing values',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['Workclass', 'Occupation', 'Relationship',
                                  'Race', 'Sex', 'Native-country'])])

In [12]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(['Income'],axis=1),df['Income'],test_size=0.25,random_state=1)

In [31]:
X_tr=tnf1.fit_transform(X_train)

In [2]:
d={'a':12,'b':32}

In [4]:
list(d.values())

[12, 32]

In [32]:
X_te=tnf1.transform(X_test)

In [35]:
X_tr[0]

array([51.0, 284211.0, 9.0, 0.0, 0.0, 35.0, ' Private', ' Prof-specialty',
       ' Unmarried', ' White', ' Female', ' United-States'], dtype=object)

In [1]:
a="Age	Workclass	Fnlwgt	Education-num	Occupation	Relationship	Race	Sex	Capital-gain	Capital-loss	Hours-per-week	Native-country"
a.replace('\t',',')

'Age,Workclass,Fnlwgt,Education-num,Occupation,Relationship,Race,Sex,Capital-gain,Capital-loss,Hours-per-week,Native-country'

In [36]:
X_train.head()

Age          Workclass  Fnlwgt  Education-num       Occupation  \
13474   51            Private  284211              9   Prof-specialty   
28958   36            Private  119957             13    Other-service   
14735   30   Self-emp-not-inc  164190             15   Prof-specialty   
13215   22          Local-gov  289982             13   Prof-specialty   
13460   41            Private  177905             14   Prof-specialty   

      Relationship    Race      Sex  Capital-gain  Capital-loss  \
13474    Unmarried   White   Female             0             0   
28958    Unmarried   Black   Female             0             0   
14735    Own-child   White     Male             0             0   
13215    Own-child   White   Female             0             0   
13460      Husband   White     Male             0             0   

       Hours-per-week  Native-country  
13474              35   United-States  
28958              35   United-States  
14735              40   United-States  
13215              35   United-States  
13460              45   United-States

In [4]:
tnf1=ColumnTransformer(transformers=[
    ("Handling Int-Missing values",SimpleImputer(),[0,2,3,8,9,10]),
    ("Handling Cat-Missing values",SimpleImputer(strategy='most_frequent'),[1,4,5,6,7,11])
],remainder='passthrough')
#[1,4,5,6,7,11]

In [46]:
X_tr=tnf1.fit_transform(X_train)
X_te=tnf1.transform(X_test)

In [53]:
X_tr

array([[51.0, 284211.0, 9.0, ..., ' White', ' Female', ' United-States'],
       [36.0, 119957.0, 13.0, ..., ' Black', ' Female', ' United-States'],
       [30.0, 164190.0, 15.0, ..., ' White', ' Male', ' United-States'],
       ...,
       [27.0, 104457.0, 13.0, ..., ' Asian-Pac-Islander', ' Male',
        ' South'],
       [59.0, 268700.0, 9.0, ..., ' White', ' Male', ' United-States'],
       [33.0, 59083.0, 13.0, ..., ' White', ' Male', ' United-States']],
      dtype=object)

In [5]:
tnf2=ColumnTransformer(transformers=[
    ('Encoding',OneHotEncoder(sparse=False,drop='first',dtype='int',handle_unknown='ignore'),slice(6,13))
],remainder='passthrough')

In [6]:
tnf3=ColumnTransformer(transformers=[
    ('Feature scaling',StandardScaler(),slice(0,76))
],remainder='passthrough')

In [54]:
k=tnf2.fit_transform(X_train)

c:\Users\new\anaconda3\envs\Feature_eng\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [58]:
X_train.head(1)

Age Workclass  Fnlwgt  Education-num       Occupation Relationship  \
13474   51   Private  284211              9   Prof-specialty    Unmarried   

         Race      Sex  Capital-gain  Capital-loss  Hours-per-week  \
13474   White   Female             0             0              35   

       Native-country  
13474   United-States

In [60]:
X_tr[0]

array([51.0, 284211.0, 9.0, 0.0, 0.0, 35.0, ' Private', ' Prof-specialty',
       ' Unmarried', ' White', ' Female', ' United-States'], dtype=object)

In [70]:
len(k[0])

75

In [71]:
len(l)

24420

In [69]:
len(l[0])

75

In [74]:
Pipe=make_pipeline(tnf1,tnf2,tnf3)

In [75]:
Pipe

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Handling Int-Missing values',
                                                  SimpleImputer(),
                                                  [0, 2, 3, 8, 9, 10]),
                                                 ('Handling Cat-Missing values',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [1, 4, 5, 6, 7, 11])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Encoding',
                                                  OneHotEncoder(drop='first',
                                                                dtype='int',
                                                                sparse=False),
                                                  slice(6, 13, None))])),
                ('columntransformer-3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Feature scaling',
                                                  StandardScaler(),
                                                  slice(0, 76, None))]))])

In [66]:
l=Pipe.fit_transform(X_train)

c:\Users\new\anaconda3\envs\Feature_eng\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [41]:
len(k[0])

17792

In [76]:
h=Pipe.fit_transform(X_train)

c:\Users\new\anaconda3\envs\Feature_eng\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [78]:
len(h[0])

75

In [95]:
Pipe=make_pipeline(tnf1,tnf2)

In [96]:
Pipe.fit_transform(X_train)

c:\Users\new\anaconda3\envs\Feature_eng\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0, 0, 1, ..., 0.0, 0.0, 35.0],
       [0, 0, 1, ..., 0.0, 0.0, 35.0],
       [0, 0, 0, ..., 0.0, 0.0, 40.0],
       ...,
       [0, 0, 1, ..., 0.0, 0.0, 40.0],
       [0, 0, 0, ..., 0.0, 0.0, 40.0],
       [0, 0, 1, ..., 0.0, 1902.0, 45.0]], dtype=object)

In [97]:
Pipe.transform(X_test)

c:\Users\new\anaconda3\envs\Feature_eng\lib\site-packages\sklearn\preprocessing\_encoders.py:228: UserWarning: Found unknown categories in columns [5] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


array([[0, 0, 0, ..., 0.0, 0.0, 66.0],
       [0, 0, 1, ..., 0.0, 0.0, 25.0],
       [0, 0, 1, ..., 27828.0, 0.0, 50.0],
       ...,
       [0, 0, 0, ..., 0.0, 0.0, 40.0],
       [0, 0, 1, ..., 0.0, 0.0, 40.0],
       [0, 0, 1, ..., 0.0, 0.0, 40.0]], dtype=object)

In [90]:
X_test.head()

Age          Workclass  Fnlwgt  Education-num          Occupation  \
9646    62   Self-emp-not-inc   26911              4       Other-service   
709     18            Private  208103              7       Other-service   
7385    25            Private  102476             13     Farming-fishing   
16671   33            Private  511517              9      Prof-specialty   
21932   36            Private  292570              7   Machine-op-inspct   

          Relationship    Race      Sex  Capital-gain  Capital-loss  \
9646     Not-in-family   White   Female             0             0   
709     Other-relative   White     Male             0             0   
7385         Own-child   White     Male         27828             0   
16671          Husband   White     Male             0             0   
21932        Unmarried   White   Female             0             0   

       Hours-per-week  Native-country  
9646               66   United-States  
709                25   United-States  
7385               50   United-States  
16671              40   United-States  
21932              40   United-States

In [93]:
df['Native-country'].value_counts()

Native-country
 United-States                 29629
 Mexico                          652
 Philippines                     213
 Germany                         141
 Canada                          123
 Puerto-Rico                     119
 El-Salvador                     110
 India                           108
 Cuba                             97
 South                            93
 England                          90
 Jamaica                          87
 China                            85
 Italy                            78
 Dominican-Republic               73
 Vietnam                          72
 Japan                            66
 Guatemala                        65
 Columbia                         63
 Poland                           61
 Taiwan                           60
 Iran                             44
 Haiti                            44
 Portugal                         38
 Nicaragua                        35
 Peru                             31
 France                

In [92]:
for i in X_test.columns:
    print(X_test[i].unique())
    print("*"*100)

[62 18 25 33 36 34 43 47 29 23 19 31 59 35 41 54 30 21 38 53 27 37 45 22
 60 39 48 57 64 28 49 40 61 56 24 26 58 51 46 75 32 68 65 44 55 42 52 76
 50 67 74 66 20 72 17 73 63 77 71 79 69 70 90 78 82 80 83 84 81]
****************************************************************************************************
[' Self-emp-not-inc' ' Private' ' Local-gov' ' Federal-gov'
 ' Self-emp-inc' ' State-gov' ' Without-pay' ' Never-worked']
****************************************************************************************************
[ 26911 208103 102476 ...  69285  86837 186473]
****************************************************************************************************
[ 4  7 13  9 10 14 11 16  3  6  8 12 15  5  2  1]
****************************************************************************************************
[' Other-service' ' Farming-fishing' ' Prof-specialty'
 ' Machine-op-inspct' ' Handlers-cleaners' ' Exec-managerial'
 ' Adm-clerical' ' Craft-repair' ' Sales' ' Tran

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
tnf4=LogisticRegression()

In [9]:
Pipe=make_pipeline(tnf1,tnf2,tnf3,tnf4)

In [10]:
Pipe

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Handling Int-Missing values',
                                                  SimpleImputer(),
                                                  [0, 2, 3, 8, 9, 10]),
                                                 ('Handling Cat-Missing values',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [1, 4, 5, 6, 7, 11])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Encoding',
                                                  OneHotEncoder(drop='first',
                                                                dtype='int',
                                                                handle_unknown='ignore',
                                                                sparse=False),
                                                  slice(6, 13, None))])),
                ('columntransformer-3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Feature scaling',
                                                  StandardScaler(),
                                                  slice(0, 76, None))])),
                ('logisticregression', LogisticRegression())])

In [13]:
Pipe.fit(X_train,y_train)

c:\Users\new\anaconda3\envs\Feature_eng\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Handling Int-Missing values',
                                                  SimpleImputer(),
                                                  [0, 2, 3, 8, 9, 10]),
                                                 ('Handling Cat-Missing values',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [1, 4, 5, 6, 7, 11])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Encoding',
                                                  OneHotEncoder(drop='first',
                                                                dtype='int',
                                                                handle_unknown='ignore',
                                                                sparse=False),
                                                  slice(6, 13, None))])),
                ('columntransformer-3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Feature scaling',
                                                  StandardScaler(),
                                                  slice(0, 76, None))])),
                ('logisticregression', LogisticRegression())])

In [14]:
ypred=Pipe.predict(X_test)

c:\Users\new\anaconda3\envs\Feature_eng\lib\site-packages\sklearn\preprocessing\_encoders.py:228: UserWarning: Found unknown categories in columns [5] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


In [16]:
from sklearn.metrics import accuracy_score,precision_score,recall_score

In [22]:
precision_score(y_test, ypred, pos_label=' >50K')

0.7004297114794352

In [24]:
recall_score(y_test,ypred, pos_label=' >50K')

0.6207834602829162

In [17]:
accuracy_score(y_test,ypred)

0.8544404864267289

# Note : Give column numbers accordingly, remember 1st tnf1 we had one set of columns length so original columns sequence you can refer, but tnf2 columns sequence or indexes may changes look accordingly  or else check each columnTransformer individually and check columns indexes and write according to that column indexes . still confused once check the above cells carefully and try out 

In [ ]:
import pickle

In [ ]:
pickle.dump(Pipe,open('pipe.pkl','wb'))